version: 2

jobs:
  build:
    docker:
      - image: streakphp/php72-cli:latest
        environment:
          COMPOSER_NO_INTERACTION: 1
          COMPOSER_ALLOW_SUPERUSER: 1
          PHPUNIT_POSTGRES_HOSTNAME: localhost
          PHPUNIT_POSTGRES_PORT: 5432
          PHPUNIT_POSTGRES_DATABASE: phpunit
          PHPUNIT_POSTGRES_USERNAME: phpunit
          PHPUNIT_POSTGRES_PASSWORD: phpunit
          PHPUNIT_REDIS_HOSTNAME: localhost
          PHPUNIT_REDIS_PORT: 6379
          PHPUNIT_REDIS_DATABASE: 0
      - image: postgres:9.4-alpine
        environment:
          POSTGRES_USER: phpunit
          POSTGRES_PASSWORD: phpunit
          POSTGRES_DB: phpunit
      - image: redis:alpine
    working_directory: ~/streak
    steps:
      - checkout

      - run: composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor/

      - run: xphp bin/phpunit

      - store_artifacts:
          path: build/code-coverage/
          destination: code-coverage/
      - store_test_results:
          path: build/

      - run: bash <(curl -s https://codecov.io/bash) -Z
