version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.1
    working_directory: ~/streak
    steps:
      - checkout

      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./codeclimate
      - run: chmod +x ./codeclimate

      - run: composer self-update
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.json" }}
            - composer-v1-
      - run: composer install -n --prefer-dist
      - save_cache:
          key: composer-v1-{{ checksum "composer.json" }}
          paths:
            - vendor/

      - run: ./codeclimate before-build
      - run: bin/phpunit
      - run: cp ./build/clover.xml ./clover.xml
      - run: ./codeclimate after-build -t clover --exit-code $?

      - store_artifacts:
          path: build/code-coverage/
          destination: code-coverage/
      - store_test_results:
          path: build/

