codecov:
  branch: master
  max_report_age: 24
  require_ci_to_pass: yes

comment:
  layout: "reach, diff, flags, files"
  behavior: new
  require_changes: false
  require_base: true
  require_head: true

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: yes
      macro: yes

coverage:
  precision: 2
  round: down
  range: "90...100"

  status:
    project:
      default:
        target: auto
        threshold: 0%
        base: auto
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: true
    patch:
      default:
        target: auto
        threshold: 0%
        base: auto
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: true
